---
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redis-enterprise-database
spec:
  memorySize: 1G
  shardCount: 1
  replication: true
  modulesList:
    - name: "search"
      version: "2.4.8"
    - name: "timeseries"
      version: "1.6.9"
